name: CI  # Workflow name shown in GitHub Actions UI

on:
  # Trigger on pushes to these branches
  push:
    branches: [ main, develop, feature/** ]
    # Skip trivial changes to speed up CI
    paths-ignore:
      - '**/*.md'
      - '.vscode/**'
      - '.idea/**'
  # Also run on pull requests into these branches
  pull_request:
    branches: [ main, develop ]
    paths-ignore:
      - '**/*.md'
      - '.vscode/**'
      - '.idea/**'

jobs:
  ci:
    runs-on: ubuntu-latest            # GitHub-hosted Linux runner
    timeout-minutes: 15               # Prevents hanging jobs

    permissions:
      contents: read                  # Minimal permissions for checkout

    concurrency:                      # Cancel older runs on the same ref
      group: ci-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout source
        uses: actions/checkout@v4     # Pull the repository code

      - name: Use Node.js 20
        uses: actions/setup-node@v4   # Install Node and enable caching
        with:
          node-version: 20
          cache: npm                  # Cache ~/.npm for faster installs

      - name: Install dependencies
        run: npm ci                   # Clean, reproducible install (uses package-lock.json)

      # ---- Optional quality gates (run only if you have these scripts) ----
      - name: Lint
        run: npm run lint --if-present    # e.g., "next lint"

      - name: Typecheck
        run: npm run typecheck --if-present  # e.g., "tsc --noEmit"

      - name: Test
        run: npm test --if-present          # e.g., "vitest run" or "jest --ci"

      # ---- Ensure production build succeeds (no deployment here) ----
      - name: Build
        run: npm run build
        env:
          NEXT_TELEMETRY_DISABLED: 1        # Optional: disable Next telemetry
          # If your build needs env vars, expose them from repo Secrets:
          # NEXT_PUBLIC_API_BASE: ${{ secrets.NEXT_PUBLIC_API_BASE }}

      # ---- Optional: upload artifacts to help debugging (e.g., .next) ----
      - name: Upload build artifact
        if: always()                         # Even if previous steps failed
        uses: actions/upload-artifact@v4
        with:
          name: next-build
          path: |
            .next
            next.config.* 
            package.json
          if-no-files-found: ignore
